# Generated by Django 5.1.3 on 2024-11-21 06:12

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0005_alter_student_locker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(unique=True, validators=[subject_app.validators.validate_subject_format])),
                ('professor', models.CharField(default='Mr. Cahan', validators=[subject_app.validators.validate_professor_name])),
                ('students', models.ManyToManyField(to='student_app.student')),
            ],
        ),
    ]
