# Generated by Django 5.1.3 on 2024-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_alter_subject_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
