# Generated by Django 5.1.3 on 2024-11-21 23:20

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0003_remove_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(validators=[subject_app.validators.validate_professor_name]),
        ),
    ]
